name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  crypto: ^3.0.6
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  rxdart: ^0.28.0
  google_fonts: ^6.2.1
  intl:
  flutter_svg:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Fraunces-Regular
      fonts:
        - asset: assets/fonts/Fraunces/Fraunces-Regular.ttf
    - family: Fraunces-SemiBold
      fonts:
        - asset: assets/fonts/Fraunces/Fraunces-SemiBold.ttf
    - family: Fraunces-Bold
      fonts:
        - asset: assets/fonts/Fraunces/Fraunces-Bold.ttf
